name: auto-clang-format
on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Clang format
        uses: DoozyX/clang-format-lint-action@v0.20
        with:
          source: "."
          exclude: "./third_party ./external"
          extensions: "h,hpp,cc,cpp"
          clangFormatVersion: 19
          inplace: True

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: ":art: Committing clang-format changes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
